### ISSUE TITLE
Different card height / jumping cards in 2021.10.0b4

### ISSUE THREAD

**Issue by noxhirsch** [esphome/dashboard#103]
In ESPHome 2021.10.0b4 the online state is hidden. Because of that, the height of the cards are different:
![image](https://user-images.githubusercontent.com/30938717/137625047-ab3ee17a-a828-4919-ad4c-4916cbc92b76.png)
While I like the more compact view - it causes all cards to jump up/down when the status of one of the upper devices changes and also doesn't look clean.

Suggestion:
Use the icon of HA binary sensor device class connectivity to show if a device is offline (with tooltip & alt text "OFFLINE"):
![image](https://user-images.githubusercontent.com/30938717/137625667-4c771766-9f15-4952-b119-3f89d4520271.png)

**Comment by noxhirsch** [comment]
I think `help-network` / `help-network-outline` fits best for `unknown`:
![image](https://user-images.githubusercontent.com/30938717/137645028-e135e4b7-590a-461e-88f4-52e422ca09fb.png)
`check-network` and `close-network` might be good alternatives to show online/offline:
![image](https://user-images.githubusercontent.com/30938717/137645092-34e3d5c8-8e30-42a2-934b-6363557d9116.png)

**Comment by balloob** [comment]
Thinking now, unknown is really just during startup of the page, maybe we can drop it? CC @jesserockz
