### ISSUE TITLE
Give us back the obvious: online state of nodes

### ISSUE THREAD

**Issue by rradar** [esphome/dashboard#142]
Please, like it was once upon the time:

![image](https://user-images.githubusercontent.com/34582688/144114716-2308d9de-0df4-48ff-b21e-9a4f1246f205.png)

Plain, simple, useful :green_heart:

**Comment by jsuanet** [comment]
Yes please💚

**Comment by mmakaay** [comment]
Nothing wrong with a green border combined with an `ONLINE` label for the color blind IMO. 💚 
I've helped quite a few people with the confusing current styling of things.
Myself, I still am having troubles getting used to the new styling. Every time I open the dashboard, I find myself thinking about what I'm seeing.
