### ISSUE TITLE
"Delete" button in GUI is too easy to misclick, needs a confirmation prompt

### ISSUE THREAD

**Issue by carldebilly** [esphome/dashboard#29]
**Describe the problem you have/What new integration you would like**
Currently there's no confirmation when deleting a device in the GUI. It's pretty scary to use.

**Please describe your use case for this integration and alternatives you've tried:**
Would like to be asked for confirmation before proceeding to the deletion of the device.

**Additional context**
Fixing this would also prevent bugs like [this one](https://github.com/esphome/issues/issues/1619).

**Comment by glmnet** [comment]
There used to be an undo button I guess

**Comment by balloob** [comment]
It's still there as migrating delete is still pending #17

**Comment by balloob** [comment]
Delete now has confirmation:

![image](https://user-images.githubusercontent.com/1444314/137256502-9cb57fb1-68aa-45c1-96e7-825915affa0a.png)
