### ISSUE TITLE
Editor scroll on mobile

### ISSUE THREAD

**Issue by bearpawmaxim** [esphome/dashboard#304]
Please add the scroll ability to the config editor on mobile devices.
I understand that there is horizontal and vertical scrollbars, but using them is uncomfortable.

**Comment by tiimsvk** [comment]
I have the same problem.  It is now not possible to edit the code on mobile at all.

**Comment by PanicRide** [comment]
FYI... the new editor's issues on mobile aren't just limited to scrolling. The ability to select text for copy/paste is no longer possible either (at least with Android).
