### ISSUE TITLE
Dashboard does not autosave when pressing install.

### ISSUE THREAD

**Issue by HACKER-3000** [esphome/dashboard#31]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

installed via pip

**ESPHome version (latest production, beta, dev branch)**

v1.19.1

**Affected component:**

**Description of problem:**

If you click the INSTALL button, the dashboard will not autosave like it did in previos versions. Kinda annoying...

**Comment by balloob** [comment]
Fix has already been released. Please update to 1.19.4.
