### ISSUE TITLE
ESPHome editor in HA change color quotes

### ISSUE THREAD

**Issue by tiimsvk** [esphome/dashboard#315]
### The problem

It is possible to change the color of the style in editor. The one in the original version 2022.8 suited me better.

### Which version of ESPHome has the issue?

2022.9.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.9.6

### What platform are you using?

ESP32

**Comment by glmnet** [comment]
Fixed in #311
