### ISSUE TITLE
No Paste command on context menu

### ISSUE THREAD

**Issue by craigueh** [esphome/dashboard#321]
Using the latest version of esphome (2022.9.2) and the latest version of Firefox (105.0.1) there is no Paste option on the context menu.
It's there on Chrome and Safari but missing on Firefox. I tried clearing browser cache but no luck.

**Comment by glmnet** [comment]
can you reproduce this issue in https://microsoft.github.io/monaco-editor/playground.html ?

If you can, then this is an issue with the editor itself, not the dashboard

**Comment by craigueh** [comment]
Indeed, I could reproduce the issue there. It's an issue with the editor itself so!

**Comment by glmnet** [comment]
Ok thanks
