### ISSUE TITLE
Adopted POE proxy remains in Dashboard as 'Discovered', and doesnt do 'Active'

### ISSUE THREAD

**Issue by Mariusthvdb** [esphome/dashboard#329]
_Originally posted by @Mariusthvdb in https://github.com/esphome/dashboard/issues/320#issuecomment-1271316764_

thought it best to post this as a separate issue, as it contains new info after initial succes

thx for the fix. Updated the Add-on to 2022.9.4  and refreshed the firmware on https://esphome.github.io/bluetooth-proxies/ 
 
I can see the devices being discovered:
<img width="1471" alt="Schermafbeelding 2022-10-07 om 10 54 06" src="https://user-images.githubusercontent.com/33354141/194514740-c4621234-5fd5-4ffc-9a56-ee7b461e555a.png">

so, I click on Adopt on the 277564, change the name to something nicer, `bluetooth-proxy-centraal` and that seems to fare well. I do notice it still compiles Wifi related lines, and an error scrolls by:

```
/data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-spi.c: In function 'spiTransferBytesNL':
/data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-spi.c:922:39: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
                 uint8_t * last_out8 = &result[c_longs-1];
                                       ^
/data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-spi.c:923:40: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
                 uint8_t * last_data8 = &last_data;
                                        ^
```
no matter that, there is success reported, and the board is online. hurray.

however, in the dashboard the discovered device is still showing after successful adoption:

<img width="1456" alt="Schermafbeelding 2022-10-07 om 10 54 12" src="https://user-images.githubusercontent.com/33354141/194515341-6f34b932-f127-4fed-a7e6-ccb0ada39000.png">

reading the process for the M5stack board does in fact take away the 'discovered' device:

<img width="1465" alt="Schermafbeelding 2022-10-07 om 11 03 52" src="https://user-images.githubusercontent.com/33354141/194516674-cf2e3e97-0ba9-4e46-aad1-a7771c9f415a.png">

finally, this is repeated in the homeassistant.log:
```
Logger: homeassistant.components.esphome
Source: components/esphome/__init__.py:263 
Integration: ESPHome (documentation, issues) 
First occurred: 10:53:09 (20 occurrences) 
Last logged: 11:08:21

Name of device olimex-bluetooth-proxy-277564 changed to bluetooth-proxy-centraal, potentially due to IP reassignment
```
and
```
Logger: aioesphomeapi.reconnect_logic
Source: runner.py:119 
First occurred: 12:30:15 (1 occurrences) 
Last logged: 12:30:15

Can't connect to ESPHome API for olimex-bluetooth-proxy-277564 @ 192.168.1.221: Server sent a different name 'bluetooth-proxy-centraal'
```

which ofc isnt the fact and seems another bug?

**Comment by Mariusthvdb** [comment]
right, so after some time, and having adopted all of my 3 boards, the discovered ones are gone. However, the Olimex boards seem no to communicate with actual devices, whihc now all show a dBm of lower than -90... while the boards are actually next to them.

My M5 stack does this better, and actually makes the connection stronger when moving towards it.

opening the Esphome dashboard now show this once more, the board is re Discovered...:

<img width="1444" alt="Schermafbeelding 2022-10-07 om 14 28 30" src="https://user-images.githubusercontent.com/33354141/194553856-03505ce5-747c-41f0-bb2f-570c3f7dc542.png">

also, when clicking the edit button, the yaml is nowhere near what the yaml files contain in the Esphome repo for these devices:

```
substitutions:
  name: "bluetooth-proxy-aanbouw"
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/olimex-esp32-poe-iso.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
```

so what is going on here?

**Comment by balloob** [comment]
The Home Assistant issue is unrelated to here. That is due to Home Assistant using the configuration name as unique ID, and so the unique ID changes. This needs to be updated to use the mac address to seamlessly allow renaming.

For discovered, I think that's a backend bug @jesserockz. The problem is that the output of `ping` contains cached devices. We should either clear that output after a rename, or have a better way of cleaning up stale devices.

Easy step to reproduce is to hit "rename" in a dropdown menu in ESPHome dashboard.

**Comment by Mariusthvdb** [comment]
can close now, seems to be fixed and no longer happening
thx.

or should that backend bug still be considered?

**Comment by balloob** [comment]
That was already addressed.
