### ISSUE TITLE
Unable to open device logs in 1.19.4 (TypeError: t.filter is not a function)

### ISSUE THREAD

**Issue by DAVe3283** [esphome/dashboard#35]
I hope this is not a duplicate, but searching for "logs" or any variation results in __every issue__ matching. Sorry in advance.
This broke somewhere after 1.19.1.

I have the add-on set to use SSL. I also have the VS Code add-on installed, which might be relevant given the mention in the logs below. I was not able to get the VSCode integration working, probably due to my DNS setup (I do not use Home Assistant for DNS, I use Windows Server 2012R2 with a real domain name for everything, so *.local will not resolve anything).

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io (Home Assistant OS 6.0, supervisor-2021.06.6, core-2021.6.4 running in a VM)
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266, probably all though
**ESPHome version (latest production, beta, dev branch)**

1.19.4 (latest as of now)
**Affected component:**

The web UI itself ([here I guess](https://esphome.io/guides/getting_started_hassio.html))

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
All devices have this issue, appears front-end related.

**Logs (if applicable):**

Browser console logs. The first 3 entries are just loading the page, the last entry is when I click on LOGS:

![image](https://user-images.githubusercontent.com/6894502/124042809-ea255800-d9c6-11eb-9e2e-1b834f361d77.png)
```
Uncaught (in promise) TypeError: t.filter is not a function
    at c.2472ed8e.js:1
```

ESPHome log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ESPHome
 ESPHome add-on for intelligently managing all your ESP8266/ESP32 devices
-----------------------------------------------------------
 Add-on version: 1.19.4
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.0  (amd64 / qemux86-64)
 Home Assistant Core: 2021.6.4
 Home Assistant Supervisor: 2021.06.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 20-nginx.sh: executing... 
[cont-init.d] 20-nginx.sh: exited 0.
[cont-init.d] 30-esphome.sh: executing... 
[cont-init.d] 30-esphome.sh: exited 0.
[cont-init.d] 40-migrate.sh: executing... 
[cont-init.d] 40-migrate.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[17:15:02] INFO: Waiting for dashboard to come up...
[services.d] done.
[17:15:02] INFO: Starting ESPHome dashboard...
INFO Starting dashboard web server on unix socket /var/run/esphome.sock and configuration dir /config/esphome...
[17:15:03] INFO: Starting NGINX...
INFO 200 GET / (0.0.0.0) 7.86ms
INFO 101 GET /ace (0.0.0.0) 0.47ms
INFO Running command 'esphome --dashboard -q vscode /config/esphome --ace'
```

**Additional information and things you've tried:**

ESPHome add-on configuration:
```yml
status_use_ping: true
ssl: true
certfile: real.FQDN.net-chain-2020.crt
keyfile: real.FQDN.net-key-2020.pem
relative_url: ''
leave_front_door_open: false
```
I have `status_use_ping: true` because mDNS does not work to/from the VLAN I keep my IOT devices in. But ping does, and this setup has been flawless until 1.19.4.

Reverting to a snapshot of 1.19.1 got things working again. I tried to restore my snapshot of 1.19.2 but that failed. Edit: removed logs of snapshot restore, that snapshot was bad for whatever reason.

**Comment by OttoWinter** [comment]
Can you try clearing the cache? So Ctrl+Shift+R, or in networks tab click checkbox to disable caching.

**Comment by DAVe3283** [comment]
> Can you try clearing the cache? So Ctrl+Shift+R, or in networks tab click checkbox to disable caching.

Yep, that worked for Chrome on the desktop. Sorry, I thought I had done that, but I think I used the wrong shortcut.

Clearing the Android app cache through system settings fixed that too. Is there some way to do it from inside the app?

**Comment by stefanroelofs** [comment]
Is this issue still open? For me the Logs button is also not working:
![image](https://user-images.githubusercontent.com/37924749/125356270-45136380-e366-11eb-8cd4-0c838bcf505d.png)

HA: 2021.7.1
espHome addon: 1.19.4
Browser: Vivaldi 4.0.2312.33
Browser: Chrome 91.0.4472.124
(I also tried the Edge browser, and that one does work)
Thanks!
