### ISSUE TITLE
Migrate editor to Lit

### ISSUE THREAD

**Issue by balloob** [esphome/dashboard#5]
`raw_package/static/js/esphome.js` is the legacy JavaScript file. Code in there needs to be refactored into Lit/TypeScript.

This issue is to track moving the editor.

**Comment by balloob** [comment]
Use for toast replacement: https://material-components.github.io/material-components-web-components/demos/snackbar/

**Comment by glmnet** [comment]
Im working on this. I have no experience with lit and roll up but managed to get the Monaco editor in place (it was an ugly fight where I lost my esteem several times). Ace is nice but this way it would look more like vscode with ESPHome add on, also syntax highlighting in ace wouldn't be with lambda coloring, in Monaco out of the box neither but I've seen oniguruma texmate grammars can be used (will be painful too)
